USE U05SnL;
ALTER TABLE address MODIFY COLUMN addressID INT(10) auto_increment;
ALTER TABLE appointment MODIFY COLUMN appointmentId INT(10) auto_increment;
ALTER TABLE appointment ADD COLUMN type TEXT;
ALTER TABLE appointment ADD COLUMN userId INT;
ALTER TABLE city MODIFY COLUMN cityId INT(10) auto_increment;
ALTER TABLE country MODIFY COLUMN countryId INT(10) auto_increment;
ALTER TABLE customer MODIFY COLUMN customerId INT(10) auto_increment;
ALTER TABLE user MODIFY COLUMN userId INT auto_increment;
ALTER TABLE user MODIFY COLUMN active TINYINT;
ALTER TABLE user DROP COLUMN lastUpdatedBy;
ALTER TABLE user ADD COLUMN lastUpdatedBy TEXT;
DROP TABLE incrementtypes;
DROP TABLE reminder;
ALTER TABLE city ADD CONSTRAINT FK_CountryCity FOREIGN KEY (countryId) REFERENCES country(countryId);
ALTER TABLE address ADD CONSTRAINT FK_CityAddress FOREIGN KEY (cityId) REFERENCES city(cityId);
ALTER TABLE customer ADD CONSTRAINT FK_AddressCustomer FOREIGN KEY (addressId) REFERENCES address(addressId);
ALTER TABLE appointment ADD CONSTRAINT FK_UserAppointment FOREIGN KEY (userId) REFERENCES user(userId);
ALTER TABLE appointment ADD CONSTRAINT FK_CustomerAppointment FOREIGN KEY (customerId) REFERENCES customer(customerId);
